# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nme')),
                ('done', models.BooleanField(verbose_name='IsDone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedDate')),
            ],
        ),
    ]
